/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshStandardMaterial } from "three";
import { useSpring, animated } from '@react-spring/three';

export function RightArrow({onClick}) {
  const { nodes, materials } = useGLTF("./modern buildings/arrowRight.gltf");
 

  const Material = new MeshStandardMaterial({metalness: .7, roughness: 0.1, color: 0x5c5c5c  })
  return (
    <animated.group dispose={null} onClick={onClick}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={Material}
        position={[1.6, 0, 5]}
        rotation={[Math.PI / 2, -Math.PI / 4, Math.PI / 2]}
        scale={[0.0075, .05, .05]}
      />
    </animated.group>
  );
}


